### ISSUE TITLE
Adding a license

### ISSUE THREAD

**Issue by kev-chien** [PatrickF1/GraceTunes#166]
Hi!

My name is Kevin - I'm a worship leader at my current church. I was looking at my old chord sheets from my college days when I used to go to GP, and noticed a gracetunes URL - and that's how I found this repo. From what I can tell, this repo is pretty awesome, has received a lot of ❤️ , and does a lot of what I'm looking for in a worship chords app.

I was wondering if I could use this repo for personal use, but I couldn't find a license in this repo. Per [open source guidelines for Github projects](https://opensource.guide/legal/#are-public-github-projects-open-source), Github public projects without a license cannot be used by anyone else without permission from the copyright holder.

> If you want others to use, distribute, modify, or contribute back to your project, you need to include an open source license.

Would you be willing to add a license to this repo? The guide I linked above has some recommendations. That would clarify the permissions for those interested in using this code.

Thank you!

**Comment by natyconnor** [comment]
Hi @kev-chien, sorry for the late response, I'm not sure if anyone is very active checking on this repo 😅 @PatrickF1 so he hopefully sees this as he'll probably have to give the final answer (and he probably has to ask some other people), but if he wants my 2 cents, I would be a proponent of adding an open source license (I'm pretty sure there's nothing we need to protect in our code), but I'm kind of an everything-should-be-open-source kind of person so I'll let Patrick give the final word.

Thanks for being considerate and asking for permission!

**Comment by PatrickF1** [comment]
Hey @kev-chien, just added a license. Out of curiosity,  what are you going to use this code for? How might GraceTunes benefit your church?

**Comment by kev-chien** [comment]
Amazing - thank you so much! 🙏 

I'd like to try to host my own instance, for use for myself, and other worship team members at my church to be able to store, edit, and print worship chords.

I currently manually edit all my chords on Google Docs, and manually transpose. GraceTunes would be a step up in functionality and save me and my team time.

**Comment by PatrickF1** [comment]
Very nice, good luck!
